### ISSUE TITLE
SNMP:: class setup failure in __constructor for Version 2c

### ISSUE THREAD

**Issue by Guyverix** [php/doc-en#1365]
From manual page: https://php.net/class.snmp

Reproducible in Ubuntu 20.04, PHP7.4, and 8.1

```
<?php
$snmpAddress="192.168.15.74";
$snmpCommunity="public";
$snmpOidValue="1.3.6.1.2.1.25.1";
$snmpVer=array(1,2);

foreach ($snmpVer as $snmpVersion) {
  echo "gettype snmpVersion " . gettype($snmpVersion) . " " . $snmpVersion . "\n";
  $session = new SNMP($snmpVersion , "$snmpAddress", "$snmpCommunity");
  $sessionResult = $session->walk("$snmpOidValue");
  echo "Session Result: " . var_dump($sessionResult) . "\n";
}
?>
```
Results identical in both 7.4 and 8.1:
```
php7.4 ./testWalker.php 
gettype snmpVersion integer 1
array(7) {
  ["iso.3.6.1.2.1.25.1.1.0"]=>
  string(42) "Timeticks: (537818649) 62 days, 5:56:26.49"
  ["iso.3.6.1.2.1.25.1.2.0"]=>
  string(45) "Hex-STRING: 07 E6 01 1D 0F 15 26 00 2D 08 00 "
  ["iso.3.6.1.2.1.25.1.3.0"]=>
  string(15) "INTEGER: 393216"
  ["iso.3.6.1.2.1.25.1.4.0"]=>
  string(130) "STRING: "BOOT_IMAGE=/boot/vmlinuz-4.15.0-162-generic root=UUID=af28cb5f-789e-48a0-8a74-43943e912480 ro quiet splash vt.handoff=1
""
  ["iso.3.6.1.2.1.25.1.5.0"]=>
  string(10) "Gauge32: 1"
  ["iso.3.6.1.2.1.25.1.6.0"]=>
  string(12) "Gauge32: 230"
  ["iso.3.6.1.2.1.25.1.7.0"]=>
  string(10) "INTEGER: 0"
}
Session Result: 
gettype snmpVersion integer 2
PHP Fatal error:  Uncaught Exception: Unknown SNMP protocol version in /opt/nmsApi/poller/noise/testWalker.php:9
Stack trace:
#0 /opt/nmsApi/poller/noise/testWalker.php(9): SNMP->__construct()
#1 {main}
  thrown in /opt/nmsApi/poller/noise/testWalker.php on line 9
```
Changing the var to string "2c", or "2" shows that it appears to be expecting an INT value, but cannot seem to figure out the v2 version:
```
gettype snmpVersion string 2c
PHP Notice:  A non well formed numeric value encountered in /opt/nmsApi/poller/noise/testWalker.php on line 9
PHP Fatal error:  Uncaught Exception: Unknown SNMP protocol version in /opt/nmsApi/poller/noise/testWalker.php:9
Stack trace:
#0 /opt/nmsApi/poller/noise/testWalker.php(9): SNMP->__construct()
#1 {main}
  thrown in /opt/nmsApi/poller/noise/testWalker.php on line 9
```
Appears to initially be called in snmp.stub.php line 88.  Unfortunately it does not seem like I can that this much further as I know even less about C than I do with PHP :)..

---

**Comment by Guyverix** [comment]
Additional testing shows that this DOES work, but does not really follow the examples, or what the constructor should be accepting: ```$session = new SNMP(SNMP::VERSION_2c, $snmpAddress, $snmpCommunity, $timeout, $retries); ```
I also notice that it is not "stringified", so am unsure how the constructor accepts SNMP::VERSION_2c at all instead of an INT value.

**Comment by Guyverix** [comment]
Actually closing since I finally see some examples going the route I tried that worked.  Assuming I misunderstood what the class constructor is really expecting when it says INT.

**Comment by cmb69** [comment]
````
php > var_dump(SNMP::VERSION_2c);
int(1)
````
So the constructor expects an int, and `SNMP::VERSION_2c` is an int. :)
